Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M1_COMP/PyAF_M1_COMP_MNG8_18.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M1_COMP/PyAF_M1_COMP_MNG8_18.log' mode='a' encoding='UTF-8'>
BENCH_DATA M1_COMP
TIME :  Date N= 44 H= 18 HEAD= [0 1 2 3 4] TAIL= [39 40 41 42 43]
SIGNAL :  MNG20 N= 44 H= 18 HEAD= [115.9 116.  123.3 123.  123. ] TAIL= [123.9 129.8 130.5 131.8 125.4]
Index  MNG20  Date
1      115.9     0
2      116.0     1
3      123.3     2
4      123.0     3
5      123.0     4
<class 'pandas.core.frame.DataFrame'>
Index: 44 entries, 1 to 44
Data columns (total 2 columns):
MNG20    44 non-null float64
Date     44 non-null int64
dtypes: float64(1), int64(1)
memory usage: 1.0+ KB
None
BENCHMARK_FAILURE 'M1_COMP_MNG20_18'
