Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M3_M_COMP/PyAF_M3_M_COMP_N2665_18.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M3_M_COMP/PyAF_M3_M_COMP_N2665_18.log' mode='a' encoding='UTF-8'>
BENCH_DATA M3_M_COMP
TIME :  Date N= 117 H= 18 HEAD= [0 1 2 3 4] TAIL= [112 113 114 115 116]
SIGNAL :  N2677 N= 117 H= 18 HEAD= [3612.4 3612.  3615.4 3631.8 3652. ] TAIL= [3621.8 3614.6 3614.6 3598.2 3589.8]
Index   N2677  Date
1      3612.4     0
2      3612.0     1
3      3615.4     2
4      3631.8     3
5      3652.0     4
<class 'pandas.core.frame.DataFrame'>
Index: 117 entries, 1 to 117
Data columns (total 2 columns):
N2677    117 non-null float64
Date     117 non-null int64
dtypes: float64(1), int64(1)
memory usage: 2.7+ KB
None
BENCHMARK_FAILURE 'M3_M_COMP_N2677_18'
