Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_CLIMATE/PyAF_M4_COMP_CLIMATE_C0556_35.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_CLIMATE/PyAF_M4_COMP_CLIMATE_C0556_35.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_CLIMATE
TIME :  Date N= 105 H= 35 HEAD= [0 1 2 3 4] TAIL= [100 101 102 103 104]
SIGNAL :  C0570 N= 105 H= 35 HEAD= [1008. 1013. 1015. 1011. 1005.] TAIL= [1005. 1006. 1015. 1003.  999.]
    C0570  Date
0  1008.0     0
1  1013.0     1
2  1015.0     2
3  1011.0     3
4  1005.0     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 105 entries, 0 to 104
Data columns (total 2 columns):
C0570    105 non-null float64
Date     105 non-null int64
dtypes: float64(1), int64(1)
memory usage: 2.5 KB
None
BENCHMARK_FAILURE 'M4_COMP_CLIMATE_C0570_35'
