Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_CLIMATE/PyAF_M4_COMP_CLIMATE_C0358_35.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_CLIMATE/PyAF_M4_COMP_CLIMATE_C0358_35.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_CLIMATE
TIME :  Date N= 258 H= 35 HEAD= [0 1 2 3 4] TAIL= [253 254 255 256 257]
SIGNAL :  C0371 N= 258 H= 35 HEAD= [1017.  972.  971. 1017. 1019.] TAIL= [1018. 1012. 1010. 1003. 1010.]
    C0371  Date
0  1017.0     0
1   972.0     1
2   971.0     2
3  1017.0     3
4  1019.0     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 258 entries, 0 to 257
Data columns (total 2 columns):
C0371    258 non-null float64
Date     258 non-null int64
dtypes: float64(1), int64(1)
memory usage: 6.0 KB
None
BENCHMARK_FAILURE 'M4_COMP_CLIMATE_C0371_35'
