Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_ECONOMICS/PyAF_M4_COMP_ECONOMICS_ECON0428_8.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_ECONOMICS/PyAF_M4_COMP_ECONOMICS_ECON0428_8.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_ECONOMICS
TIME :  Date N= 235 H= 8 HEAD= [0 1 2 3 4] TAIL= [230 231 232 233 234]
SIGNAL :  ECON0440 N= 235 H= 8 HEAD= [ 0.5 -1.2 -2.9  1.5  3.6] TAIL= [60.8 71.5 90.7 15.9 11. ]
   ECON0440  Date
0       0.5     0
1      -1.2     1
2      -2.9     2
3       1.5     3
4       3.6     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 235 entries, 0 to 234
Data columns (total 2 columns):
ECON0440    235 non-null float64
Date        235 non-null int64
dtypes: float64(1), int64(1)
memory usage: 5.5 KB
None
BENCHMARK_FAILURE 'M4_COMP_ECONOMICS_ECON0440_8'
