Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_ECONOMICS/PyAF_M4_COMP_ECONOMICS_ECON0920_18.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_ECONOMICS/PyAF_M4_COMP_ECONOMICS_ECON0920_18.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_ECONOMICS
TIME :  Date N= 46 H= 18 HEAD= [0 1 2 3 4] TAIL= [41 42 43 44 45]
SIGNAL :  ECON0931 N= 46 H= 18 HEAD= [100.4 101.  100.7 100.7 102.3] TAIL= [98.  96.2 96.9 97.5 99.1]
   ECON0931  Date
0     100.4     0
1     101.0     1
2     100.7     2
3     100.7     3
4     102.3     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 46 entries, 0 to 45
Data columns (total 2 columns):
ECON0931    46 non-null float64
Date        46 non-null int64
dtypes: float64(1), int64(1)
memory usage: 1.1 KB
None
BENCHMARK_FAILURE 'M4_COMP_ECONOMICS_ECON0931_18'
