Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_ECONOMICS/PyAF_M4_COMP_ECONOMICS_ECON0908_18.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_ECONOMICS/PyAF_M4_COMP_ECONOMICS_ECON0908_18.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_ECONOMICS
TIME :  Date N= 47 H= 18 HEAD= [0 1 2 3 4] TAIL= [42 43 44 45 46]
SIGNAL :  ECON0918 N= 47 H= 18 HEAD= [99.7 99.8 98.8 98.1 98.7] TAIL= [100.3 101.4 101.4 101.1 100.7]
   ECON0918  Date
0      99.7     0
1      99.8     1
2      98.8     2
3      98.1     3
4      98.7     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 47 entries, 0 to 46
Data columns (total 2 columns):
ECON0918    47 non-null float64
Date        47 non-null int64
dtypes: float64(1), int64(1)
memory usage: 1.1 KB
None
BENCHMARK_FAILURE 'M4_COMP_ECONOMICS_ECON0918_18'
