Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_ECONOMICS/PyAF_M4_COMP_ECONOMICS_ECON1064_18.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_ECONOMICS/PyAF_M4_COMP_ECONOMICS_ECON1064_18.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_ECONOMICS
TIME :  Date N= 46 H= 18 HEAD= [0 1 2 3 4] TAIL= [41 42 43 44 45]
SIGNAL :  ECON1071 N= 46 H= 18 HEAD= [102.9 102.8 103.  102.4 102.1] TAIL= [102.6 103.1 103.1 103.4 103.7]
   ECON1071  Date
0     102.9     0
1     102.8     1
2     103.0     2
3     102.4     3
4     102.1     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 46 entries, 0 to 45
Data columns (total 2 columns):
ECON1071    46 non-null float64
Date        46 non-null int64
dtypes: float64(1), int64(1)
memory usage: 1.1 KB
None
BENCHMARK_FAILURE 'M4_COMP_ECONOMICS_ECON1071_18'
