Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_ECONOMICS/PyAF_M4_COMP_ECONOMICS_ECON0921_18.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_ECONOMICS/PyAF_M4_COMP_ECONOMICS_ECON0921_18.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_ECONOMICS
TIME :  Date N= 46 H= 18 HEAD= [0 1 2 3 4] TAIL= [41 42 43 44 45]
SIGNAL :  ECON0937 N= 46 H= 18 HEAD= [96.8 97.  96.7 97.2 98. ] TAIL= [101.6 100.8 101.8 102.2  99.2]
   ECON0937  Date
0      96.8     0
1      97.0     1
2      96.7     2
3      97.2     3
4      98.0     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 46 entries, 0 to 45
Data columns (total 2 columns):
ECON0937    46 non-null float64
Date        46 non-null int64
dtypes: float64(1), int64(1)
memory usage: 1.1 KB
None
BENCHMARK_FAILURE 'M4_COMP_ECONOMICS_ECON0937_18'
